# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - main
    - ado*
    exclude:
      - ado-azure-pipelines
  paths:
    exclude:
    - metadata
  tags:
    include:
    - v1.*
    exclude:
    - v1.0

pool:
  name: Azure Pipelines

steps:
- script: echo Hello, $(NAME)!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo ping 127.0.0.1 -n 10
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'BASH Task says: Hello world'
